"""Usage: python -m balatro_ai_v2.live run --episodes 5 --output runs/dev-001"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from balatro_ai_v2.balatrobot.client import BalatroBotClient
from balatro_ai_v2.live.runner import RunConfig, make_policy, replay, run_batch


def main() -> int:
    parser = argparse.ArgumentParser(description="Real Balatro baseline evaluation and offline decision replay")
    commands = parser.add_subparsers(dest="command", required=True)
    run = commands.add_parser("run", help="Play a fixed-seed Red Deck / White Stake batch")
    run.add_argument("--output", required=True, type=Path, help="New directory; existing output is never overwritten")
    run.add_argument("--episodes", type=int, default=5)
    run.add_argument("--split", choices=("dev", "heldout"), default="dev")
    run.add_argument("--policy", choices=("baseline", "strategic", "search"), default="baseline")
    run.add_argument("--profile-mode", choices=("all_unlocked", "career"), default="all_unlocked")
    run.add_argument("--seeds", nargs="+", help="Explicit unique 1–8 character seeds (otherwise generated by split)")
    run.add_argument("--seed-offset", type=int, default=0)
    run.add_argument("--host", default="127.0.0.1")
    run.add_argument("--port", type=int, default=12346)
    run.add_argument("--timeout", type=float, default=30.0, help="RPC timeout; mutating calls are never retried")
    run.add_argument("--max-decisions", type=int, default=2000)
    run.add_argument("--endless", action="store_true", help="Continue after Ante 8, tracking the persistent victory flag")
    run.add_argument("--max-ante", type=int, default=16, help="In endless mode, stop on entering the following ante")
    run.add_argument("--reset", action="store_true", help="Allow replacing an already active game")
    compare = commands.add_parser("replay", help="Recompute decisions offline, without a game connection")
    compare.add_argument("trajectory", type=Path)
    compare.add_argument("--policy", choices=("baseline", "strategic", "search"), help="Compare a different policy with the recorded actions")
    args = parser.parse_args()
    try:
        if args.command == "replay":
            result = replay(args.trajectory, make_policy(args.policy) if args.policy else None)
            print(json.dumps(result, indent=2))
            return 0 if not result["differences"] and result["complete_trace"] else 1
        if args.episodes < 1 or args.seed_offset < 0 or args.timeout <= 0:
            parser.error("episodes and timeout must be positive; seed-offset must be nonnegative")
        prefix = "D" if args.split == "dev" else "H"
        seeds = args.seeds or [f"{prefix}{i:07d}" for i in range(args.seed_offset, args.seed_offset + args.episodes)]
        config = RunConfig(split=args.split, policy=args.policy, max_decisions=args.max_decisions,
                           endless=args.endless, max_ante=args.max_ante, expected_profile=args.profile_mode)
        summary = run_batch(BalatroBotClient(host=args.host, port=args.port, timeout=args.timeout),
                            seeds, args.output, config, reset=args.reset)
        print(f"Summary: {args.output / 'summary.json'}")
        if summary.get("batch_error"):
            print(summary["batch_error"])
        return 1 if (summary.get("batch_error") or summary["status_counts"].get("error")
                     or summary["status_counts"].get("truncated")) else 0
    except (OSError, ValueError, RuntimeError) as exc:
        parser.exit(2, f"error: {exc}\n")


if __name__ == "__main__":
    raise SystemExit(main())
